import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Icons } from "@/components/Icons";

import "./globals.css";
import { NavigationMenuDemo } from "../components/NavBar1";
import { NavigationMenuDemo1 } from "../components/NavBar2";
import { NavigationMenuDemo3 } from "../components/NavBar3";
import Link from "next/link";
import React, { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });
const SearchBar = React.lazy(() => import('@/components/SearchBar'));
export const metadata: Metadata = {
  title: "Compare Building Materials",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative min-h-screen isolate overflow-hidden border-b border-gray-200 bg-stone-900 text-amber-500">
        <svg
          className='absolute inset-0 -z-10 h-full w-full stroke-amber-600 [mask-image:radial-gradient(100%_100%_at_top_right,white,transparent)]'
          aria-hidden='true'>
          <defs>
              <pattern
              id='0787a7c5-978c-4f66-83c7-11c213f99cb7'
              width={200}
              height={200}
              x='50%'
              y={-1}
              patternUnits='userSpaceOnUse'>
              <path d='M.5 200V.5H200' fill='none' />
              </pattern>
          </defs>
          <rect
              width='100%'
              height='100%'
              strokeWidth={0}
              fill='url(#0787a7c5-978c-4f66-83c7-11c213f99cb7)'
          />
          </svg>
          <div className="mx-auto max-w-7xl px-6 pb-24 pt-10 sm:pb-32 lg:flex gap-16 lg:px-8 lg:py-24 text-amber-500">
            <div className="h-full w-full flex flex-col items-center gap-4">
              <Icons.Hammer className="h-16 w-16"/>
              <Link href="/" passHref>
              <h1 className="tracking-tight text-4xl sm:text-6xl font-bold">
                Compare Building Items
              </h1>
              </Link>
              <p className="max-w-xl text-center text-lg text-amber-600">
                From builders to builders
              </p>
              {/* <div style={{ marginBottom: '-10px' }} className=""><NavigationMenuDemo/></div>
              <div style={{ marginBottom: '-10px' }} className=""><NavigationMenuDemo1/></div>
              <div ><NavigationMenuDemo3/></div> */}
              <div className=" text-stone-800 mx-auto mt-16 w-full max-w-2x1 flex flex-col">
              <Suspense fallback={<div>Loading...</div>}>
                <SearchBar />
              </Suspense>
                {children}
              </div>
              <footer className=" text-amber-500 text-center p-4 mt-8">
              <p className="text-sm">
                 {new Date().getFullYear()} | Made By <a className="hover:text-amber-100 hover:underline" target="_blank" href="https://github.com/wlodzimierrr">Wlodzimierrr</a>
              </p>
            </footer>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
