name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker image for compare_frontend
        run: docker build -t ghcr.io/wlodzimierrr/compare_frontend:latest ./compare_frontend
      
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/wlodzimierrr/compare_frontend:latest
      
      - name: Configure Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 416.0.0'
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          project_id: ${{ secrets.GCE_PROJECT }}
          export_default_credentials: true
      
      - name: SSH into Google Cloud VM and update Docker image
        run: |
          gcloud compute ssh ${GCE_INSTANCE} --zone ${GCE_INSTANCE_ZONE} --command "docker stop compare_frontend && docker rm compare_frontend && docker pull ghcr.io/wlodzimierrr/compare_frontend:latest && docker run -d --name compare-frontend -p 3000:3000 ghcr.io/wlodzimierrr/compare_frontend:latest"
        env:
          GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
          GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}
